packages:
  - 'packages/*'

catalog:
  '@noble/hashes': 2.2.0
  '@scure/base': ^2.2.0
  tiny-secp256k1: ^2.2.3
  undici: ^8.9.0
allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  unrs-resolver: true
